import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@repo/ui/components/sonner";
import { Kanit } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";

const kanit = Kanit({
    subsets: ["latin"],
    variable: "--font-kanit",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "All In Order",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} w-full h-dvh min-h-dvh dark`}>
        <TRPCReactProvider>
            {children}
        </TRPCReactProvider>
        <Toaster/>
      </body>
    </html>
  );
}
