import type {Metadata} from "next";
import {Kanit} from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import type React from "react";
import Navbar from "@/app/navbar";

const kanit = Kanit({weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    // Preload user data while rendering the layout

    return (
        <html lang="en">
        <body className={kanit.className + " dark bg-background text-foreground"}>
        <Providers>

            <div className="w-full h-screen flex flex-col items-stretch justify-stretch">
                <header>
                    <Navbar/>
                </header>
                <main className="flex-grow w-full h-full">
                    {children}
                </main>
            </div>
        </Providers>
        </body>
        </html>
    );
}
